FROM node:alpine

# Criar o diretorio
WORKDIR /app

# Copie o package.json e o lock.json
COPY package*.json ./

RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Exponha a porta na qual o aplicativo escutará
EXPOSE 3333